 #ifndef GAMEPARAMETERS_H
#define GAMEPARAMETERS_H

#define CHUNK_SIZE 16
#define WORLD_HEIGHT 256
#define WORLD_FLOOR 40
#define WATER_LEVEL 55
#define WORLD_SEED 42

#define CHUNK_LOAD_DISTANCE 15
#define SCENE_UPDATE_FREQ 15

#endif // GAMEPARAMETERS_H